name: "Run linter"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash -l {0}
jobs:
  sanity_check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Conda environment from environment-dev.yml
        uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          environment-file: environment-dev.yml
      - name: "Run black lint"
        run: make lint/black
      - name: "Run isort check"
        run: make lint/isort
