name: "Run linter"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash -l {0}
jobs:
  sanity_check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Install Conda environment from environment-dev.yml
        uses: mamba-org/setup-micromamba@4b9113af4fba0e9e1124b252dd6497a419e7396d # v1.11.0
        with:
          environment-file: environment-dev.yml
      - name: "Run black lint"
        run: make lint/black
      - name: "Run isort check"
        run: make lint/isort
